### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by staminna** [dreamerkumar/bizsitegenie#1]
Hi

I am using the file upload widget running in production mode on mac os and nothing gets uploaded or returns an error on the interface. Looking at the logs

$ cat run_app_in_prod_mode_after_mongod_is_running_results.log 

```
START ---> run_app_in_prod_mode_after_mongod_is_running
COMMAND ---> cd website
COMMAND ---> NODE_ENV=production forever server.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Application loaded using the "production" environment configuration
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/MAMP/htdocs/mean/bizsitegenie/website/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
MEAN.JS application started on port 3000
error: Forever detected script exited with code: 0
error: Script restart attempt #1
Application loaded using the "production" environment configuration
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/MAMP/htdocs/mean/bizsitegenie/website/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
MEAN.JS application started on port 3000
error: Forever detected script exited with code: 0
error: Script restart attempt #2
Application loaded using the "production" environment configuration
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/MAMP/htdocs/mean/bizsitegenie/website/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
MEAN.JS application started on port 3000
Jorge:bizsitegenie jorge$ 
```

**Comment by dreamerkumar** [comment]
You are right. These logs are not for the file upload. I don't know if you got any errors on your chrome debugger. Worth checking it out. I wanna make sure, you did the necessary steps for upload to work. The Framework uses S3 for uploads. You will need to create an account on Amazon S3 and then provide the url to your S3 bucket. This information goes in the configuration section of the Framework. Let me know if you need more help with this.

**Comment by staminna** [comment]
Here is the call stack on the chrome console.
![screenshot 2016-10-01 12 59 04](https://cloud.githubusercontent.com/assets/515180/19013930/ed2f35e4-87d6-11e6-90d1-fe7c2b06827f.png)
I just created a S3 account. Will each user get his own permission/folder inside the S3?

**Comment by dreamerkumar** [comment]
Permission is set at the application level. So it should work for all user accounts.

**Comment by staminna** [comment]
Thanks for quick reply. 
I'm not sure about the path, but I created a folder inside the bucket named "Genie" and set if up on the s3 config file as 'Genie/' and the bucket 'fortebuck' name as a string in single quotes.
![aws s3 bucket config](https://cloud.githubusercontent.com/assets/515180/19221971/92ebc1f4-8e45-11e6-8b0f-1a4875771ebd.png)
I don't think it would upload directly to https://s3.amazonaws.com/fortebuck. Is this URL where it is supposed to work?

I'm really enjoying what you have here. I'm looking forward to working with you.

Thanks.

**Comment by dreamerkumar** [comment]
You cannot upload directly. There is an access key and a secret key that goes with the request. 

These are the three places where you will need to set the values in your config file. After that, make sure you restart your web application.

![image](https://cloud.githubusercontent.com/assets/10477607/19225984/20916540-8e73-11e6-993e-1cd3945fc3bc.png)

Also, you will need to setup your amazon s3 server to handle CORS request. Here is an article explaining in detail all the steps you will need to do: https://www.terlici.com/2015/05/23/uploading-files-s3.html

**Comment by staminna** [comment]
I wasn't using the standard US servers.
